[project]
name = "arxivnewsletter"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "beautifulsoup4>=4.13.5",
    "strands-agents[anthropic]>=1.6.0",
    "strands-agents-tools>=0.2.5",
]
